import {
  Star, Shield, Zap, Heart, Target, Users, Clock, Check, Award, Globe,
  Briefcase, Settings, Wrench, Lightbulb, TrendingUp, Rocket, Lock, Cpu,
  BarChart3, MessageSquare, Trophy, Crown, Gem, CheckCircle, ArrowRight,
  Phone, Mail, MapPin, Calendar, Camera, Eye, Smile, ThumbsUp, Coffee,
  Utensils, Building, Home, Key, Search, Compass, Layers, Package, Palette,
  PenTool, Share2, ShoppingCart, Tag, Truck, Umbrella, Video, Wifi, BookOpen,
  FileText, Headphones, Monitor, Scissors, Sun, Moon, Leaf, TreePine,
  Dumbbell, Activity, Stethoscope, Pill, Brain, Baby, Dog, Music, Sparkles,
  Flame, Droplets, Wind, Mountain, Waves, Anchor, CircleDot, Crosshair,
  Fingerprint, HandMetal, Hammer, PaintBucket, Ruler, Scale, Siren, Timer,
  UserCheck, ClipboardCheck, BadgeCheck, ShieldCheck, HeartPulse, Bolt,
  Cloud, HelpCircle, LineChart, BarChart, PieChart, Cog, CircleHelp,
  type LucideIcon
} from "lucide-react";

const baseIconMap: Record<string, LucideIcon> = {
  star: Star,
  shield: Shield,
  zap: Zap,
  heart: Heart,
  target: Target,
  users: Users,
  clock: Clock,
  check: Check,
  "check-circle": CheckCircle,
  award: Award,
  globe: Globe,
  briefcase: Briefcase,
  settings: Settings,
  wrench: Wrench,
  lightbulb: Lightbulb,
  trending: TrendingUp,
  "trending-up": TrendingUp,
  rocket: Rocket,
  lock: Lock,
  cpu: Cpu,
  chart: BarChart3,
  "bar-chart": BarChart3,
  message: MessageSquare,
  "message-square": MessageSquare,
  trophy: Trophy,
  crown: Crown,
  gem: Gem,
  arrow: ArrowRight,
  "arrow-right": ArrowRight,
  phone: Phone,
  mail: Mail,
  email: Mail,
  "map-pin": MapPin,
  location: MapPin,
  calendar: Calendar,
  camera: Camera,
  eye: Eye,
  smile: Smile,
  "thumbs-up": ThumbsUp,
  coffee: Coffee,
  utensils: Utensils,
  food: Utensils,
  building: Building,
  home: Home,
  house: Home,
  key: Key,
  search: Search,
  compass: Compass,
  layers: Layers,
  package: Package,
  palette: Palette,
  "pen-tool": PenTool,
  pen: PenTool,
  share: Share2,
  "shopping-cart": ShoppingCart,
  cart: ShoppingCart,
  tag: Tag,
  truck: Truck,
  delivery: Truck,
  umbrella: Umbrella,
  video: Video,
  wifi: Wifi,
  book: BookOpen,
  "book-open": BookOpen,
  file: FileText,
  "file-text": FileText,
  headphones: Headphones,
  monitor: Monitor,
  screen: Monitor,
  scissors: Scissors,
  sun: Sun,
  moon: Moon,
  leaf: Leaf,
  tree: TreePine,
  plant: Leaf,
  eco: Leaf,
  dumbbell: Dumbbell,
  fitness: Dumbbell,
  gym: Dumbbell,
  activity: Activity,
  health: Activity,
  stethoscope: Stethoscope,
  medical: Stethoscope,
  pill: Pill,
  medicine: Pill,
  brain: Brain,
  baby: Baby,
  dog: Dog,
  pet: Dog,
  music: Music,
  sparkle: Sparkles,
  sparkles: Sparkles,
  magic: Sparkles,
  flame: Flame,
  fire: Flame,
  hot: Flame,
  droplet: Droplets,
  water: Droplets,
  wind: Wind,
  air: Wind,
  mountain: Mountain,
  waves: Waves,
  ocean: Waves,
  anchor: Anchor,
  circle: CircleDot,
  crosshair: Crosshair,
  precision: Crosshair,
  fingerprint: Fingerprint,
  identity: Fingerprint,
  hand: HandMetal,
  hammer: Hammer,
  paint: PaintBucket,
  color: PaintBucket,
  ruler: Ruler,
  measure: Ruler,
  scale: Scale,
  balance: Scale,
  siren: Siren,
  emergency: Siren,
  ambulance: Siren,
  timer: Timer,
  stopwatch: Timer,
  "user-check": UserCheck,
  verified: UserCheck,
  "clipboard-check": ClipboardCheck,
  clipboard: ClipboardCheck,
  "badge-check": BadgeCheck,
  badge: BadgeCheck,
  "shield-check": ShieldCheck,
  "heart-pulse": HeartPulse,
  heartbeat: HeartPulse,
  pulse: HeartPulse,
  bolt: Bolt,
  lightning: Bolt,
  electric: Bolt,
  cloud: Cloud,
  "help-circle": HelpCircle,
  help: HelpCircle,
  question: CircleHelp,
  "line-chart": LineChart,
  graph: LineChart,
  "bar-chart-2": BarChart,
  "pie-chart": PieChart,
  gear: Cog,
  cog: Cog,
  configure: Cog,
};

const fuzzyKeywords: Record<string, string> = {
  tooth: "sparkles",
  dental: "sparkles",
  implant: "wrench",
  "x-ray": "eye",
  xray: "eye",
  robot: "cpu",
  arm: "hand",
  needle: "compass",
  protect: "shield",
  guard: "shield",
  grow: "trending",
  growth: "trending",
  speed: "zap",
  fast: "zap",
  love: "heart",
  care: "heart",
  team: "users",
  group: "users",
  people: "users",
  money: "tag",
  dollar: "tag",
  price: "tag",
  cost: "tag",
  secure: "lock",
  privacy: "lock",
  idea: "lightbulb",
  think: "brain",
  smart: "brain",
  ai: "cpu",
  tech: "cpu",
  digital: "monitor",
  online: "globe",
  world: "globe",
  travel: "compass",
  navigate: "compass",
  direction: "compass",
  beauty: "sparkles",
  salon: "scissors",
  spa: "droplet",
  food: "utensils",
  restaurant: "utensils",
  cook: "flame",
  chef: "utensils",
  drink: "coffee",
  clean: "sparkles",
  wash: "droplet",
  legal: "scale",
  law: "scale",
  justice: "scale",
  build: "hammer",
  construct: "hammer",
  repair: "wrench",
  fix: "wrench",
  design: "palette",
  art: "palette",
  creative: "palette",
  write: "pen",
  edit: "pen",
  learn: "book",
  education: "book",
  study: "book",
  ship: "truck",
  send: "truck",
  workout: "dumbbell",
  exercise: "dumbbell",
  train: "dumbbell",
  run: "activity",
  walk: "activity",
  nature: "leaf",
  green: "leaf",
  organic: "leaf",
  photo: "camera",
  image: "camera",
  picture: "camera",
  call: "phone",
  ring: "phone",
  contact: "phone",
  date: "calendar",
  event: "calendar",
  schedule: "calendar",
  buy: "shopping-cart",
  shop: "shopping-cart",
  purchase: "shopping-cart",
  save: "tag",
  discount: "tag",
  offer: "tag",
  safe: "shield",
  trust: "shield",
  premium: "star",
  quality: "star",
  best: "star",
  top: "star",
  excellent: "award",
  achieve: "award",
  win: "trophy",
  champion: "trophy",
  luxury: "crown",
  elite: "crown",
  vip: "crown",
  special: "gem",
  unique: "gem",
  rare: "gem",
  support: "headphones",
  help: "headphones",
  music: "music",
  sound: "music",
  audio: "headphones",
  video: "video",
  film: "video",
  internet: "wifi",
  connect: "wifi",
  network: "wifi",
  home: "home",
  house: "home",
  property: "building",
  office: "building",
  company: "building",
  baby: "baby",
  child: "baby",
  kid: "baby",
  pet: "dog",
  animal: "dog",
  vet: "stethoscope",
  doctor: "stethoscope",
  nurse: "stethoscope",
  hospital: "stethoscope",
  wellness: "heart-pulse",
  vital: "heart-pulse",
  relax: "sun",
  warm: "sun",
  bright: "sun",
  night: "moon",
  sleep: "moon",
  calm: "moon",
};

export function getIcon(iconName: string | undefined, fallback: LucideIcon = Star): LucideIcon {
  if (!iconName) return fallback;

  const normalized = iconName.toLowerCase().trim().replace(/\s+/g, "-");

  const direct = baseIconMap[normalized];
  if (direct) return direct;

  const withoutSuffix = normalized.replace(/-icon$/, "");
  if (baseIconMap[withoutSuffix]) return baseIconMap[withoutSuffix];

  for (const [key, icon] of Object.entries(baseIconMap)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return icon;
    }
  }

  const parts = normalized.split("-");
  for (const part of parts) {
    if (part.length < 3) continue;
    if (baseIconMap[part]) return baseIconMap[part];
  }

  for (const part of parts) {
    if (part.length < 3) continue;
    const fuzzyMatch = fuzzyKeywords[part];
    if (fuzzyMatch && baseIconMap[fuzzyMatch]) return baseIconMap[fuzzyMatch];
  }

  for (const [keyword, mappedIcon] of Object.entries(fuzzyKeywords)) {
    if (normalized.includes(keyword)) {
      const icon = baseIconMap[mappedIcon];
      if (icon) return icon;
    }
  }

  return fallback;
}

export { baseIconMap };
